export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_BY_ID = 'GET_POSTS_BY_ID'
export const ADD_POST = 'ADD_POST'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'

export const GET_REVIEWS = 'GET_REVIEWS'
export const GET_REVIEWS_BY_ID = 'GET_REVIEW_BY_ID'
export const CREATE_REVIEW = 'CREATE_REVIEW'
export const ADD_REVIEW = 'ADD_REVIEW'
export const UPDATE_REVIEW = 'UPDATE_REVIEW'
export const DELETE_REVIEW = 'DELETE_REVIEW'
