export const GET_DESTINATIONS = 'GET_DESTINATIONS'
export const GET_DESTINATION_LOADING_TYPE = 'GET_DESTINATION_LOADING_TYPE'
export const GET_REVIEWS = 'GET_REVIEWS'
export const GET_COMMENTS = 'GET_COMMENTS'