export const GET_POSTS = 'GET_POSTS';
export const POST_LOADING_TYPE = 'POST_LOADING_TYPE';
export const GET_POSTS_BY_ID = 'GET_POSTS_BY_ID';
export const POST_BY_ID_LOADING_TYPE = 'POST_BY_ID_LOADING_TYPE';
export const GET_COMMENTS = 'GET_COMMENTS';
export const COMMENTS_LOADING_TYPE = 'COMMENTS_LOADING_TYPE';
export const CREATE_COMMENTS = 'CREATE_COMMENTS';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
