export const DESTINATION_LOADING_TYPE = 'DESTINATION_LOADING_TYPE';
export const GET_DESTINATIONS = 'GET_DESTINATION';
export const REVIEW_LOADING_TYPE = 'REVIEW_LOADING_TYPE';
export const GET_REVIEWS = 'GET_DEPARTMENT_REVIEWS';
